name: CI-Tests

on:
  push:
#    branches:
#    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
  build:
    environment: Debugging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel pytest pytest-cov
      #pip install -r requirements.txt
    - name: Install lalsuite
      run: |
        pip install scipy==1.4.1
        pip install numpy==1.18.5
        pip install matplotlib==3.2.1
        pip install lscsoft-glue==2.0.0
        pip install ligo-segments==1.2.0
        pip install six==1.15.0
        pip install pyOpenSSL==19.1.0
        pip install pyparsing==2.4.7
        pip install cycler==0.10.0
        pip install kiwisolver==1.2.0
        pip install cryptography==2.9.2
        pip install cffi==1.14.0
        pip install pycparser==2.20
        pip install zipp==3.1.0
        pip install importlib-resources==1.6.0
        pip install lalsuite
      env:
        ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
    - name: Display Python, pip, and setuptools version
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        python -c "import setuptools; print(f'setuptools {setuptools.__version__}')"
    - name: Run Tests
      run: |
        pytest
